### ISSUE TITLE
'jenv' 不是内部或外部命令，也不是可运行的程序 或批处理文件

### ISSUE THREAD

**Issue by buxinshou** [chroblert/JC-jEnv#3]
![image](https://user-images.githubusercontent.com/31057024/160984457-f1af4147-3d00-4f48-93f9-849f11c93539.png)

---

![image](https://user-images.githubusercontent.com/31057024/160984511-75ba77e0-fb36-4e00-a5a8-41b3ba2045c3.png)

---

![image](https://user-images.githubusercontent.com/31057024/160984979-065a55d4-36b5-4b6e-9c3c-c0cc41eca79b.png)

**Comment by chroblert** [comment]
环境变量path里面设的应该是路径，删去最后的文件名试试看-------- 原始邮件 --------发件人： buxinshou ***@***.***>日期： 2022年3月31日周四 13:46收件人： chroblert/JC-jEnv ***@***.***>抄送： Subscribed ***@***.***>主    题： [chroblert/JC-jEnv] 'jenv' 不是内部或外部命令，也不是可运行的程序 或批处理文件 (Issue #3)

**Comment by buxinshou** [comment]
> 环境变量path里面设的应该是路径，删去最后的文件名试试看-------- 原始邮件 --------发件人： buxinshou ***@***.***>日期： 2022年3月31日周四 13:46收件人： chroblert/JC-jEnv ***@***.***>抄送： Subscribed ***@***.***>主 题： [chroblert/JC-jEnv] 'jenv' 不是内部或外部命令，也不是可运行的程序 或批处理文件 (Issue #3) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



你好，`path`中删除最后的文件名后,系统是`win11 64位`

---

![image](https://user-images.githubusercontent.com/31057024/160989358-ab4b174c-e874-4617-acc8-7e6170f4cc2d.png)

---

**Comment by chroblert** [comment]
改变文件编码(ANSI或UTF8)试试看
多运行几次，看之后是否正常

**Comment by buxinshou** [comment]
> 改变文件编码(ANSI或UTF8)试试看 多运行几次，看之后是否正常


新建一个空白文档，将内容复制进去，另存为`utf-8`格式文件后可以用啦。谢谢。
